### ISSUE TITLE
"Colorful 100 mg/dl" - rainbow color does not go away

### ISSUE THREAD

**Issue by emp-00** [MrJordanRoth/NS2Win#16]
@MrJordanRoth : I have tried to fix this in the last days and tried at least 5 different "solutions" but none worked to full extent. Yesterday I chose to revert to your initial **[MeasureGlucose]** code but, as it turned out, this already seems to have this issue. What happens? Whenever I hit the "lucky 100 mg/dl" the rainbow color is displayed. Good. However, after polling the next value 99.9999% sure not @100 mg/dl any more - the rainbow color remains. Does this also happen for you or is this related to some other code section??

![image001](https://user-images.githubusercontent.com/60714349/195436990-95bd4227-c1df-49b5-9b94-66f9a8a8ef0a.png)

It's such a simple task to adjust colors for 3 different conditions (in a normal programming language) but in Rainmeter code this is a try&error-task for me that failed too many times already. I probably should read the manuals but maybe you can help me here...

My problem here is, that of course you don't get a "lucky 100" every half hour, at least I don't. So testing + fixing this is no fun...

```
[MeasureGlucose]
Measure=WebParser
URL=[MeasureSite]
StringIndex=2
; ***Change BG Color to Red
IfCondition=MeasureGlucose < #LowGlucoseAlert#
IfTrueAction=[!SetOption MeterGlucose FontColor "255,0,0"]
IfFalseAction=[!SetOption meterGlucose FontColor "255,255,255"]
; ***Change BG Color to Orange
IfCondition2=MeasureGlucose > #HighGlucoseAlert#
IfTrueAction2=[!SetOption meterGlucose FontColor "229,172,64"]
; ***Change BG Color to Colorful-Gradient @100
IfCondition3=MeasureGlucose = 100
IfTrueAction3=[!SetOption meterGlucose InlineSetting "GradientColor | 180 | 255,0,0,255 ; 0.0 | 0,255,0,255 ; 0.5 | 0,0,255,255 ; 1.0"]
```

**Comment by MrJordanRoth** [comment]
I can't replicate that issue, is this in the code you posted in a zip? I'll take a look at it tonight.

**Comment by MrJordanRoth** [comment]
@emp-00,

I wonder if this had something to do with how I was using a refresh and the new code you implemented isn't refreshing the entire skin. My suggestion may be to add the [!redraw] to the end of the IfTrueAction:

```
[MeasureGlucose]
Measure=WebParser
URL=[MeasureSite]  
StringIndex=2  
; ***Change BG Color to Red  
IfCondition=MeasureGlucose < #LowGlucoseAlert#  
IfTrueAction=[!SetOption MeterGlucose FontColor "255,0,0"][!Redraw]  
IfFalseAction=[!SetOption meterGlucose FontColor "255,255,255"][!Redraw]  
; ***Change BG Color to Orange  
IfCondition2=MeasureGlucose > #HighGlucoseAlert#  
IfTrueAction2=[!SetOption meterGlucose FontColor "229,172,64"][!Redraw]  
; ***Change BG Color to Colorful-Gradient @100  
IfCondition3=MeasureGlucose = 100  
IfTrueAction3=[!SetOption meterGlucose InlineSetting "GradientColor | 180 | 255,0,0,255 ; 0.0 | 0,255,0,255 ; 0.5 | 0,0,255,255 ; 1.0"][!Redraw]
```

I'm thinking it may trigger those changes when your delta gets updated. Another way for testing is to define a variable for MeasureGlucose and set it up as a reading (allow the rest of the code to pull the delta and trend arrows). Also, I just noticed this and I'm not sure if it is accurate but there is a case error with MeterGlucose - I have it with an uppercase M and a lowercase m and I'm not sure if that could potentially cause an issue with it too - so you may update those to match what the actual meter is.

**Comment by emp-00** [comment]
@MrJordanRoth : That's a good explanation - of course the 1min Refresh functionality avoids this issue...

Feedback to your proposal:
- That's exactly what I already tried: Adding "!Redraw", adding "DynamicVariables=1" and even adding IfFalseAction with "back to white color" after all 3 conditions.
- Maybe I made a mistake or have not changed those options 100% systematically (maybe two together) but for sure none of them solved this issue
- Honestly, I'm surprised that such a "simple" task with 3 conditions is so complicated to implement with the desired functionality

I guess we have to continue to experiment but this is not fun... :-0. I will try out your concrete proposal and let you know... Also thinking about asking the Rainmeter cracks @forum.rainmeter.net ... :-)

**Comment by MrJordanRoth** [comment]
It wouldn't hurt to ask the question there, my guess it has something to do with thr refresh but nothing is jumping out at me.

**Comment by emp-00** [comment]
@MrJordanRoth : I have found a working solution. Argh, this was a freaking odyssey! Rainmeter scripts really are a different world, this is not a programming language but, well, something special.

```
[MeasureGlucose]
Measure=WebParser
URL=[MeasureSite]
StringIndex=2
; ***Change BG Color to Red
IfCondition=MeasureGlucose < #LowGlucoseAlert#
IfTrueAction=[!SetOption meterGlucose FontColor 255,0,0]
; ***Change BG Color to Orange
IfCondition2=MeasureGlucose > #HighGlucoseAlert#
IfTrueAction2=[!SetOption meterGlucose FontColor 229,172,64]
; ***Change BG Color to Colorful-Gradient @100
IfCondition3=MeasureGlucose = 100
IfTrueAction3=[!SetOption meterGlucose InlineSetting "GradientColor | 180 | 255,0,0,255 ; 0.0 | 0,255,0,255 ; 0.5 | 0,0,255,255 ; 1.0"]
; ***Change BG Color to White if "in-range" AND not @100
IfCondition4=((MeasureGlucose >= #LowGlucoseAlert#) && (MeasureGlucose <= #HighGlucoseAlert#)) && (MeasureGlucose <> 100)
IfTrueAction4=[!SetOption meterGlucose FontColor 250,250,250]
OnUpdateAction=[!UpdateMeter meterGlucose][!Redraw]
; Added OnUpdateAction to make sure the "red" condition get's reverted, this remained red (orange back to white worked without!)
; Added Condition4 to set color to White if "in-range", now we have 4 explicit conditions for all cases and no need for IfFalseAction, and THIS works!
```

**Comment by emp-00** [comment]
Issue closed. 

Why I'm so sure? I simply changed the variables "low/highglucosealert" to around my current BG level and thus was able to test the problematic range changes from "red to white" and "orange to white". Finally I changed the "100" in the code to my current bg value => got the rainbow color and waited till the next reading => WHITE.

WTF - I did it! Finally :-P
