### ISSUE TITLE
Secure NS2Win connection to nightscout with API_SECRET or token

### ISSUE THREAD

**Issue by emp-00** [MrJordanRoth/NS2Win#8]
Dear @MrJordanRoth - thank you very much for the great NS2Win plugin to Rainmeter. It's working perfectly but there's one problem: The script only works on nightscout repositories which are "open" for reading to the whole internet. In detail this means, that it's mandatory to set AUTH_DEFAULT_ROLES="**readable**". Otherwise NS2Win currently cannot access the data via the pebble api. Obviously this is not a safe setting since everybody with the nightscout url can see the completely private data.

Suggestion: Could you implement secure access via authentication with the API_SECRET or ideally an access token?
Here's how this works: https://nightscout.github.io/nightscout/security/#create-a-token

I just tested this with my AUTH_DEFAULT_ROLES="**denied**" setting. This api call returns only the last BG entry, so preferably we'd use this for parsing: **https://[your-nightscout-server-url]/api/v1/entries.json?count=1&token=[your-token-string]**

This is where I'm lost currently -> how does the "RegExp" in line 40 of the NS2Win.ini script need to be configured to work with the above api output?

For comparison 1) "pebble api" output example:
`{"status":[{"now":1664915998034}],"bgs":[{"sgv":"84","trend":4,"direction":"Flat","datetime":1664915722580,"bgdelta":-6,"battery":"86","iob":"0.59","bwp":"-0.31","bwpo":65,"cob":0}],"cals":[]}`

For comparison 2) "api/v1/entries.json?count=1" output example:
`[{"_id":"633c9910cdbc97b5c92e50e2","device":"xDrip-DexcomG5 G6 Native","date":1664915722580,"dateString":"2022-10-04T20:35:22.580Z","sgv":84,"delta":-6.005,"direction":"Flat","type":"sgv","filtered":78890,"unfiltered":75840,"rssi":100,"noise":1,"sysTime":"2022-10-04T20:35:22.580Z","utcOffset":120,"mills":1664915722580}]
`

Many thanks for looking into this and thereby improving the NS2Win user's nightscout database security. Happy to discuss, let me know if I can contribute or answer any questions you might have.

**Comment by MrJordanRoth** [comment]
@emp-00 thanks for the suggestion, I haven't looked at this for awhile but I do see where this would be important. Let me look into this and update the code to include AUTH.

**Comment by MrJordanRoth** [comment]
@emp-00, can you change the following in the .ini file for NS2Win:
Line 26: NightScoutURL=https://YOURNSDOMAIN/?token=YOURTOKEN
Line 39: URL=#NightScoutURL#/pebble

In Line 26 you will need to enter your website for NS and the token you configured as Readable. Line 39 should just be a simple copy/paste.

Let me know if that works for you please.

**Comment by MrJordanRoth** [comment]
@emp-00, I think this can be accomplished with two simple changes in the .ini file.

Paste the following under Line 26:
NightScoutToken=/?token=ENTERNSTOKEN

Change Line 40: 
URL=#NightScoutBaseURL#pebble#NightScoutToken#

Can you give it a test to see if this works?

**Comment by emp-00** [comment]
@MrJordanRoth : THANK YOU - confirmed, this works like a charm! So the "?token=" command actually also works for the pebble api, that's super-great (I would have thought we'd need to switch to the /api/v1).

Thanks again, much appreciated!

**Comment by MrJordanRoth** [comment]
You're welcome!
